
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - searxng
    environment:
      - SEARXNG_URL=http://searxng:8080
  searxng:
    image: searxng/searxng:latest
    ports:
      - "8082:8080"